/**
 * Auto-generated by `supabase gen types typescript` (via MCP).
 * Do not edit by hand — regenerate with the Supabase MCP when schema changes.
 *
 * Source of truth: the project's migrations in Supabase.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      coop_sessions: {
        Row: {
          created_at: string
          guest_id: string | null
          host_id: string
          id: string
          join_code: string
          state: Json
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          guest_id?: string | null
          host_id: string
          id?: string
          join_code: string
          state?: Json
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          guest_id?: string | null
          host_id?: string
          id?: string
          join_code?: string
          state?: Json
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      crib_visits: {
        Row: {
          host_id: string
          id: number
          visited_at: string
          visitor_id: string
        }
        Insert: {
          host_id: string
          id?: number
          visited_at?: string
          visitor_id: string
        }
        Update: {
          host_id?: string
          id?: number
          visited_at?: string
          visitor_id?: string
        }
        Relationships: []
      }
      fan_relationships: {
        Row: {
          artist_id: string
          became_fan_at: string
          fan_id: string
        }
        Insert: {
          artist_id: string
          became_fan_at?: string
          fan_id: string
        }
        Update: {
          artist_id?: string
          became_fan_at?: string
          fan_id?: string
        }
        Relationships: []
      }
      player_events: {
        Row: {
          created_at: string
          energy_delta: number
          event_type: string
          id: number
          target_id: string | null
          user_id: string
          xp_delta: number
        }
        Insert: {
          created_at?: string
          energy_delta?: number
          event_type: string
          id?: number
          target_id?: string | null
          user_id: string
          xp_delta?: number
        }
        Update: {
          created_at?: string
          energy_delta?: number
          event_type?: string
          id?: number
          target_id?: string | null
          user_id?: string
          xp_delta?: number
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar: string
          created_at: string
          id: string
          username: string | null
        }
        Insert: {
          avatar?: string
          created_at?: string
          id: string
          username?: string | null
        }
        Update: {
          avatar?: string
          created_at?: string
          id?: string
          username?: string | null
        }
        Relationships: []
      }
      song_endorsements: {
        Row: {
          created_at: string
          id: string
          song_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          song_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          song_id?: string
          user_id?: string
        }
        Relationships: []
      }
      song_publications: {
        Row: {
          artist_id: string
          artist_name: string
          audio_url: string | null
          bpm: number | null
          duration_sec: number | null
          id: string
          key_root: string | null
          published_at: string
          retired_at: string | null
          title: string
          waveform_url: string | null
        }
        Insert: {
          artist_id: string
          artist_name: string
          audio_url?: string | null
          bpm?: number | null
          duration_sec?: number | null
          id?: string
          key_root?: string | null
          published_at?: string
          retired_at?: string | null
          title: string
          waveform_url?: string | null
        }
        Update: {
          artist_id?: string
          artist_name?: string
          audio_url?: string | null
          bpm?: number | null
          duration_sec?: number | null
          id?: string
          key_root?: string | null
          published_at?: string
          retired_at?: string | null
          title?: string
          waveform_url?: string | null
        }
        Relationships: []
      }
      song_ratings: {
        Row: {
          created_at: string
          song_id: string
          stars: number
          user_id: string
        }
        Insert: {
          created_at?: string
          song_id: string
          stars: number
          user_id: string
        }
        Update: {
          created_at?: string
          song_id?: string
          stars?: number
          user_id?: string
        }
        Relationships: []
      }
      songs: {
        Row: {
          bars: number
          bpm: number
          collaborators: string[]
          created_at: number
          id: string
          key_root: string
          layers: Json
          name: string
          pitch_score: number | null
          tags: string[]
          template_id: string
          user_id: string
          vocal_blob_url: string | null
        }
        Insert: {
          bars: number
          bpm: number
          collaborators?: string[]
          created_at: number
          id: string
          key_root: string
          layers?: Json
          name: string
          pitch_score?: number | null
          tags?: string[]
          template_id: string
          user_id: string
          vocal_blob_url?: string | null
        }
        Update: {
          bars?: number
          bpm?: number
          collaborators?: string[]
          created_at?: number
          id?: string
          key_root?: string
          layers?: Json
          name?: string
          pitch_score?: number | null
          tags?: string[]
          template_id?: string
          user_id?: string
          vocal_blob_url?: string | null
        }
        Relationships: []
      }
      tamagotchi_state: {
        Row: {
          last_seen_at: number
          mood: string
          needs: Json
          songs_abandoned: number
          songs_finished: number
          streak_days: number
          updated_at: string
          user_id: string
        }
        Insert: {
          last_seen_at?: number
          mood?: string
          needs?: Json
          songs_abandoned?: number
          songs_finished?: number
          streak_days?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          last_seen_at?: number
          mood?: string
          needs?: Json
          songs_abandoned?: number
          songs_finished?: number
          streak_days?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      template_publications: {
        Row: {
          id: string
          name: string
          producer_id: string
          published_at: string
          sounds: Json
        }
        Insert: {
          id?: string
          name: string
          producer_id: string
          published_at?: string
          sounds?: Json
        }
        Update: {
          id?: string
          name?: string
          producer_id?: string
          published_at?: string
          sounds?: Json
        }
        Relationships: []
      }
      user_stats: {
        Row: {
          energy: number
          energy_updated_at: string
          level: number
          longest_session_ms: number
          longest_streak: number
          total_songs_abandoned: number
          total_xp: number
          unlocked_achievements: string[]
          updated_at: string
          user_id: string
          vocal_count: number
        }
        Insert: {
          energy?: number
          energy_updated_at?: string
          level?: number
          longest_session_ms?: number
          longest_streak?: number
          total_songs_abandoned?: number
          total_xp?: number
          unlocked_achievements?: string[]
          updated_at?: string
          user_id: string
          vocal_count?: number
        }
        Update: {
          energy?: number
          energy_updated_at?: string
          level?: number
          longest_session_ms?: number
          longest_streak?: number
          total_songs_abandoned?: number
          total_xp?: number
          unlocked_achievements?: string[]
          updated_at?: string
          user_id?: string
          vocal_count?: number
        }
        Relationships: []
      }
    }
    Views: {
      song_publication_stats: {
        Row: {
          artist_id: string | null
          artist_name: string | null
          audio_url: string | null
          avg_stars: number | null
          bpm: number | null
          duration_sec: number | null
          endorsement_count: number | null
          key_root: string | null
          published_at: string | null
          rating_count: number | null
          song_id: string | null
          title: string | null
          waveform_url: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      earn_xp_capped: {
        Args: {
          p_daily_xp_cap: number
          p_event_type: string
          p_target_id?: string
          p_xp: number
        }
        Returns: {
          daily_xp_earned: number
          new_xp: number
          xp_awarded: number
        }[]
      }
      get_live_energy: {
        Args: { p_energy_max?: number; p_regen_interval_seconds?: number }
        Returns: {
          base_energy: number
          energy_updated_at: string
          level: number
          live_energy: number
          total_xp: number
        }[]
      }
      rate_song: {
        Args: { p_song_id: string; p_stars: number }
        Returns: {
          daily_xp_earned: number
          new_xp: number
          xp_awarded: number
        }[]
      }
      spend_energy: {
        Args: {
          p_cost: number
          p_energy_max?: number
          p_event_type: string
          p_regen_interval_seconds?: number
          p_target_id?: string
          p_xp?: number
        }
        Returns: {
          message: string
          new_energy: number
          new_xp: number
          success: boolean
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
