import type { SoundOption } from "./types";

/**
 * The seed sound library. Every option here has been "curated" to sound good
 * with every other option in the same tag family. In production the Producer
 * role would expand this. For the prototype, these synth variants are
 * generated by audio/engine.ts.
 *
 * Names are intentionally playful ("boooom", "tss", "waaah") per the
 * instructions doc: sound is named as it sounds, not by file name.
 */
export const SOUNDS: SoundOption[] = [
  // ---- Kicks ----
  { id: "k-boom", kind: "kick", name: "boom", glyph: "💥", variant: "boom", tags: ["rap", "boom-bap"], vibe: "classic head-nod" },
  { id: "k-trap", kind: "kick", name: "doof", glyph: "🪩", variant: "trap", tags: ["trap", "pop-rap"], vibe: "double-time trap thump" },
  { id: "k-halftime", kind: "kick", name: "thhump", glyph: "🫀", variant: "halftime", tags: ["drill", "trap"], vibe: "slow, heavy, half-time" },
  { id: "k-bounce", kind: "kick", name: "bounce", glyph: "🦘", variant: "bounce", tags: ["pop-rap", "dance"], vibe: "hop-hop-hop" },

  // ---- Snares ----
  { id: "s-clap", kind: "snare", name: "clap", glyph: "👏", variant: "clap", tags: ["rap", "pop-rap"], vibe: "big hand-clap on 2 and 4" },
  { id: "s-rim", kind: "snare", name: "tik", glyph: "🥢", variant: "rim", tags: ["trap", "rap"], vibe: "dry rimshot, tight" },
  { id: "s-halftime", kind: "snare", name: "kraaa", glyph: "🔊", variant: "halftime", tags: ["drill"], vibe: "one big snare on the 3" },

  // ---- Hats ----
  { id: "h-eighths", kind: "hat", name: "tss-tss", glyph: "✨", variant: "eighths", tags: ["rap", "boom-bap"], vibe: "straight 8ths, chill" },
  { id: "h-trills", kind: "hat", name: "trrrr", glyph: "🌀", variant: "trills", tags: ["trap"], vibe: "16th trill, trap staple" },
  { id: "h-skip", kind: "hat", name: "skrrr", glyph: "💨", variant: "skip", tags: ["pop-rap"], vibe: "skipping triplet feel" },
  { id: "h-sixteenths", kind: "hat", name: "ttttt", glyph: "🧨", variant: "sixteenths", tags: ["drill", "trap"], vibe: "relentless 16ths" },

  // ---- 808s ----
  { id: "b-root", kind: "808", name: "wooom", glyph: "🛸", variant: "root", tags: ["trap", "rap"], vibe: "root note, simple and heavy" },
  { id: "b-move", kind: "808", name: "wub-wub", glyph: "🌊", variant: "move", tags: ["trap", "pop-rap"], vibe: "moves with the melody" },
  { id: "b-long", kind: "808", name: "woooooom", glyph: "🌌", variant: "long", tags: ["drill", "ambient"], vibe: "long, held, atmospheric" },

  // ---- Samples ----
  { id: "sam-soul", kind: "sample", name: "soul loop", glyph: "🎷", variant: "soul-chop", tags: ["boom-bap", "rap"], vibe: "chopped soul, Kanye-style" },
  { id: "sam-dream", kind: "sample", name: "dream pad", glyph: "☁️", variant: "dreamy", tags: ["pop-rap", "ambient"], vibe: "airy, open, Travis-y" },
  { id: "sam-dark", kind: "sample", name: "dark keys", glyph: "🖤", variant: "dark-keys", tags: ["drill", "trap"], vibe: "minor, heavy, menacing" },
  { id: "sam-neon", kind: "sample", name: "neon stab", glyph: "🟣", variant: "neon", tags: ["pop-rap", "electronic"], vibe: "bright synth stab" },

  // ---- Melodies ----
  { id: "m-bell", kind: "melody", name: "bells", glyph: "🔔", variant: "bell", tags: ["trap", "pop-rap"], vibe: "bright bell lead" },
  { id: "m-pluck", kind: "melody", name: "pluck", glyph: "🪕", variant: "pluck", tags: ["rap", "drill"], vibe: "short plucky lead" },
  { id: "m-flute", kind: "melody", name: "flute", glyph: "🎶", variant: "flute", tags: ["trap", "rap"], vibe: "breathy melody line" },
];

/* -------------------------------------------------------------------------- */
/* Real file-based sounds — your GRVD Sounds folder, served from public/      */
/* -------------------------------------------------------------------------- */

export const REAL_SOUNDS: SoundOption[] = [
  // Drums (full loops)
  { id: "r-drums-150",    kind: "drums",  name: "vanessa",    glyph: "🥁", variant: "boom",     tags: ["trap", "rap"],    vibe: "punchy full loop · 150 bpm",   fileUrl: "/sounds/drums/drums_150.wav",     nativeBpm: 150 },
  { id: "r-drums-160",    kind: "drums",  name: "magic",      glyph: "✨", variant: "trap",     tags: ["trap", "drill"],  vibe: "crisp, snappy · 160 bpm",       fileUrl: "/sounds/drums/drums_160.wav",     nativeBpm: 160 },
  { id: "r-drums-165-Fm", kind: "drums",  name: "told u so",  glyph: "🔥", variant: "halftime", tags: ["trap"],           vibe: "hard drums + 808 · 165 bpm Fm", fileUrl: "/sounds/drums/drums_165_Fm.wav",  nativeBpm: 165 },

  // Hi-hats
  { id: "r-hat-150",  kind: "hat", name: "organic", glyph: "🌿", variant: "eighths",   tags: ["rap", "trap"],   vibe: "natural hi-hat loop · 150 bpm", fileUrl: "/sounds/hihat/hat_150.wav", nativeBpm: 150 },
  { id: "r-hat-160",  kind: "hat", name: "monitor", glyph: "📡", variant: "sixteenths", tags: ["drill", "trap"], vibe: "hi-hat monitor loop · 160 bpm", fileUrl: "/sounds/hihat/hat_160.wav", nativeBpm: 160 },
  { id: "r-hat-128",  kind: "hat", name: "segway",  glyph: "🛴", variant: "skip",       tags: ["rap"],           vibe: "swing hat · 128 bpm",           fileUrl: "/sounds/hihat/hat_128.wav", nativeBpm: 128 },

  // 808s
  { id: "r-808-150-Dsm", kind: "808", name: "jump",   glyph: "🛸", variant: "root", tags: ["trap"],           vibe: "808 loop · 150 bpm · D#m",  fileUrl: "/sounds/808/808_150_Dsm.wav", nativeBpm: 150 },
  { id: "r-808-144-Em",  kind: "808", name: "hound",  glyph: "🐺", variant: "move", tags: ["trap", "rap"],    vibe: "808 bass loop · 144 bpm · Em", fileUrl: "/sounds/808/808_144_Em.wav",  nativeBpm: 144 },
  { id: "r-808-144-Fm",  kind: "808", name: "werk",   glyph: "💜", variant: "long", tags: ["rap", "pop-rap"], vibe: "808 starter · 144 bpm · Fm",  fileUrl: "/sounds/808/808_144_Fm.wav",  nativeBpm: 144 },

  // Samples / melodic loops
  { id: "r-bells-Fm",     kind: "sample", name: "paradise", glyph: "☁️", variant: "soul-chop",  tags: ["pop-rap", "ambient"], vibe: "ethereal bells pad · 100 bpm · Fm", fileUrl: "/sounds/samples/bells_100_Fm.wav",    nativeBpm: 100 },
  { id: "r-melodic-Gm",   kind: "sample", name: "melodic",  glyph: "🎹", variant: "dreamy",     tags: ["trap", "rap"],        vibe: "melodic loop · 140 bpm · Gm",       fileUrl: "/sounds/samples/melodic_140_Gm.wav",  nativeBpm: 140 },
  { id: "r-sample-Bm",    kind: "sample", name: "without",  glyph: "🖤", variant: "dark-keys",  tags: ["drill", "trap"],      vibe: "dark sample · 85 bpm · Bm",         fileUrl: "/sounds/samples/sample_85_Bm.wav",    nativeBpm: 85  },
  { id: "r-vinyl-Em",     kind: "sample", name: "vinyl cut",glyph: "🎙️", variant: "neon",       tags: ["boom-bap", "rap"],    vibe: "vinyl chop · 90 bpm · Em",          fileUrl: "/sounds/samples/vinyl_90_Em.wav",     nativeBpm: 90  },
];

export const ALL_SOUNDS: SoundOption[] = [...REAL_SOUNDS, ...SOUNDS];

export const SOUNDS_BY_KIND = ALL_SOUNDS.reduce(
  (acc, s) => {
    (acc[s.kind] ??= []).push(s);
    return acc;
  },
  {} as Record<string, SoundOption[]>
);

export function getSound(id: string): SoundOption | undefined {
  return ALL_SOUNDS.find((s) => s.id === id);
}
